# permissions for end users to view kluctlmultideployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kluctlmultideployment-viewer-role
rules:
- apiGroups:
  - flux.kluctl.io
  resources:
  - kluctlmultideployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flux.kluctl.io
  resources:
  - kluctlmultideployments/status
  verbs:
  - get
