# permissions for end users to view kluctldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kluctldeployment-viewer-role
rules:
- apiGroups:
  - kluctl.io
  resources:
  - kluctldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kluctl.io
  resources:
  - kluctldeployments/status
  verbs:
  - get
