# permissions for end users to edit kluctlmultideployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kluctlmultideployment-editor-role
rules:
- apiGroups:
  - flux.kluctl.io
  resources:
  - kluctlmultideployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.kluctl.io
  resources:
  - kluctlmultideployments/status
  verbs:
  - get
