apiVersion: flux.kluctl.io/v1alpha1
kind: KluctlMultiDeployment
metadata:
  name: microservices-demo-multi
spec:
  interval: 5m
  path: "./microservices-demo/3-templating-and-multi-env/"
  sourceRef:
    kind: GitRepository
    name: microservices-demo

  # Specifies a regex to be matched against the project's targets. A KluctlDeployment will be created for each
  # matching target.
  targetPattern: local|test|feature-.*

  template:
    spec:
      interval: 5m
      timeout: 2m
      prune: true
      # kluctl targets specify the expected context name, which does not necessarily match the context name
      # found while it is deployed via the controller. This means we must pass a kubeconfig to kluctl that has the
      # context renamed to the one that it expects.
      renameContexts:
        - oldContext: default
          newContext: kind-kind
